version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "7000:3000"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mgdata:/data/db

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo_db:27017/
volumes:
  mgdata:
