# docker-compose.yml
version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - mongo_db
        #condition: service_healthy 
  mongo_db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ipl
      # Create a new database. Please note, the
      # /docker-entrypoint-initdb.d/init.js has to be executed
      # in order for the database to be created
      # MONGO_INITDB_DATABASE: exoplanets
    volumes: 
      - data:/data/db
    #  - ./initdb:/docker-entrypoint-initdb.d
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U postgres"]
  #    interval: 30s
  #    timeout: 30s
  #    retries: 3
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ipl
      ME_CONFIG_MONGODB_URL: mongodb://root:ipl@mongo_db:27017/
volumes: 
  data:


